development:
  adapter: postgresql
  encoding: utf8
  database: slovencina_development
  username: root
  password: ruebe
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: slovencina_test
  username: root
  password: ruebe
  host: localhost