development:
  adapter: postgresql
  encoding: utf8
  database: slovencina_development
  username: liesk
  password: appka
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: slovencina_test
  username: liesk
  password: appka
  host: localhost